### ISSUE TITLE
crash when using column families

### ISSUE THREAD

**Issue by philmes** [linxGnu/grocksdb#143]
I suspect this is a RocksDB bug, but posting here in case it's not. I can reliably trigger a segfault using the program below. It does not cause a segfault on OSX.

Any ideas?

Versions:

```
github.com/linxGnu/grocksdb v1.8.12
rocksdb: 8.9.1
```

RocksDB build:

```
export DEBUG_LEVEL=0
export USE_RTTI=1

make shared_lib -j 8
make install-shared
```

OS: 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

Kernel:

```
6.5.0-1014-gcp
```

Reproducible test:

```go
package main

import (
	"github.com/linxGnu/grocksdb"
	"os"
)

func main() {
	dir, err := os.MkdirTemp("/tmp", "rdb")
	if err != nil {
		panic(err)
	}

	rdb, cf := setupSimple(dir)

	key := []byte("test")
	err = rdb.PutCF(grocksdb.NewDefaultWriteOptions(), cf, key, nil)
	if err != nil {
		panic(err)
	}

	rdb.Close()

	rdb, cf = setupSimple(dir)

	rdb.GetCF(grocksdb.NewDefaultReadOptions(), cf, key)

}

const (
	DefaultCF  = "default"
	MetadataCF = "MetadataDB"
)

func setupSimple(dir string) (*grocksdb.DB, *grocksdb.ColumnFamilyHandle) {
	cfNames := []string{DefaultCF, MetadataCF}
	cfOpts := []*grocksdb.Options{defaultOpts(), defaultOpts()}

	rdb, cfHandles, err := grocksdb.OpenDbColumnFamilies(defaultOpts(), dir, cfNames, cfOpts)

	if err != nil {
		panic(err)
	}

	return rdb, cfHandles[1]
}

func defaultOpts() *grocksdb.Options {
	opts := grocksdb.NewDefaultOptions()
	opts.SetCreateIfMissingColumnFamilies(true)
	opts.SetCreateIfMissing(true)

	return opts
}
```

segfault:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7fa73b8fcb2d]

runtime stack:
runtime.throw({0x4e698f?, 0x0?})
        /opt/go/1.20.7/go/src/runtime/panic.go:1047 +0x5d fp=0x7ffcd05e0758 sp=0x7ffcd05e0728 pc=0x45387d
runtime.sigpanic()
        /opt/go/1.20.7/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7ffcd05e07b8 sp=0x7ffcd05e0758 pc=0x468369

goroutine 1 [syscall]:
runtime.cgocall(0x4b9170, 0xc00005bd70)
        /opt/go/1.20.7/go/src/runtime/cgocall.go:157 +0x5c fp=0xc00005bd48 sp=0xc00005bd10 pc=0x42557c
github.com/linxGnu/grocksdb._Cfunc_rocksdb_get_cf(0x7fa73ac080b8, 0x7fa73ac7f1c0, 0x7fa73ac08038, 0xc00001a128, 0x4, 0xc00001a1b8, 0xc000014048)
        _cgo_gotypes.go:3033 +0x4d fp=0xc00005bd70 sp=0xc00005bd48 pc=0x4b37ed
github.com/linxGnu/grocksdb.(*DB).GetCF.func1(0xc0000061a0?, 0x200000003?, 0xc0000061a0?, 0xc000028000?, {0xc00001a128?, 0x4, 0xc00005be58?}, 0x4255d1?, 0x4bd260?)
        /home/spin/go/pkg/mod/github.com/linx!gnu/grocksdb@v1.8.12/db.go:613 +0x112 fp=0xc00005bdf0 sp=0xc00005bd70 pc=0x4b5272
github.com/linxGnu/grocksdb.(*DB).GetCF(0x7fa73ac7f1c0?, 0x12?, 0x4dfa9a?, {0xc00001a128, 0x4, 0x4})
        /home/spin/go/pkg/mod/github.com/linx!gnu/grocksdb@v1.8.12/db.go:613 +0xc5 fp=0xc00005be90 sp=0xc00005bdf0 pc=0x4b5065
main.main()
        /home/spin/src/github.com/Shopify/customer-data-platform/cmd/crash/main.go:26 +0x165 fp=0xc00005bf80 sp=0xc00005be90 pc=0x4b7625
runtime.main()
        /opt/go/1.20.7/go/src/runtime/proc.go:250 +0x207 fp=0xc00005bfe0 sp=0xc00005bf80 pc=0x4561a7
runtime.goexit()
        /opt/go/1.20.7/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x480da1
```

native backtrace via gdb:

```
#0  musable (mem=0x7fffa778a020) at ./malloc/malloc.c:5129
#1  __malloc_usable_size (m=0x7fffa778a020) at ./malloc/malloc.c:5141
#2  0x00007ffff7c46370 in rocksdb::BlockContents::usable_size (this=0x7fffa778c000) at ./table/format.h:372
#3  rocksdb::Block::usable_size (this=0x7fffa778c000) at ./table/block_based/block.h:169
#4  rocksdb::Block::ApproximateMemoryUsage (this=this@entry=0x7fffa778c000) at table/block_based/block.cc:1304
#5  0x00007ffff7c8a356 in rocksdb::BlockBasedTable::PutDataBlockToCache<rocksdb::Block_kData> (this=this@entry=0x7fffa7e00080, cache_key=..., block_cache=..., out_parsed_block=out_parsed_block@entry=0x7fffce0c4bf0, uncompressed_block_contents=..., compressed_block_contents=...,
    block_comp_type=rocksdb::kNoCompression, uncompression_dict=..., memory_allocator=0x0, get_context=0x7fffce0c56d0) at table/block_based/block_based_table_reader.cc:1385
#6  0x00007ffff7c92194 in rocksdb::BlockBasedTable::MaybeReadBlockAndLoadToCache<rocksdb::Block_kData> (this=this@entry=0x7fffa7e00080, prefetch_buffer=prefetch_buffer@entry=0x0, ro=..., handle=..., uncompression_dict=..., for_compaction=false, out_parsed_block=0x7fffce0c4bf0,
    get_context=0x7fffce0c56d0, lookup_context=0x7fffce0c4ec0, contents=0x0, async_read=false, use_block_cache_for_lookup=true) at table/block_based/block_based_table_reader.cc:1666
#7  0x00007ffff7c92780 in rocksdb::BlockBasedTable::RetrieveBlock<rocksdb::Block_kData> (this=this@entry=0x7fffa7e00080, prefetch_buffer=prefetch_buffer@entry=0x0, ro=..., handle=..., uncompression_dict=..., out_parsed_block=0x7fffce0c4bf0, get_context=0x7fffce0c56d0,
    lookup_context=0x7fffce0c4ec0, for_compaction=false, use_cache=true, async_read=false, use_block_cache_for_lookup=true) at table/block_based/block_based_table_reader.cc:1808
#8  0x00007ffff7c93132 in rocksdb::BlockBasedTable::NewDataBlockIterator<rocksdb::DataBlockIter> (this=this@entry=0x7fffa7e00080, ro=..., handle=..., input_iter=input_iter@entry=0x7fffce0c50d0, block_type=block_type@entry=rocksdb::BlockType::kData,
    get_context=get_context@entry=0x7fffce0c56d0, lookup_context=0x7fffce0c4ec0, prefetch_buffer=0x0, for_compaction=false, async_read=false, s=..., use_block_cache_for_lookup=true) at ./table/block_based/block_based_table_reader_impl.h:89
#9  0x00007ffff7c8492b in rocksdb::BlockBasedTable::Get (this=0x7fffa7e00080, read_options=..., key=..., get_context=0x7fffce0c56d0, prefix_extractor=<optimized out>, skip_filters=false) at table/block_based/block_based_table_reader.cc:2272
#10 0x00007ffff7adb13f in rocksdb::TableCache::Get (this=this@entry=0x7ffff680baa0, options=..., internal_comparator=..., file_meta=..., k=..., get_context=0x7fffce0c56d0, block_protection_bytes_per_key=0 '\000',
    prefix_extractor=std::shared_ptr<const rocksdb::SliceTransform> (empty) = {...}, file_read_hist=0x7ffff697c000, skip_filters=false, level=0, max_file_size_for_l0_meta_pin=100663296) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#11 0x00007ffff7b1fa64 in rocksdb::Version::Get (this=0x7ffff696c400, read_options=..., k=..., value=0x7fffce0c5eb0, columns=0x0, timestamp=timestamp@entry=0x0, status=0x7fffce0c59f0, merge_context=0x7fffce0c5a30, max_covering_tombstone_seq=0x7fffce0c59d8,
    pinned_iters_mgr=0x7fffce0c5b20, value_found=0x0, key_exists=0x0, seq=0x0, callback=0x0, is_blob=0x0, do_merge=true) at db/version_set.cc:2420
#12 0x00007ffff79a660e in rocksdb::DBImpl::GetImpl (this=0x1542900, read_options=..., key=..., get_impl_options=...) at db/db_impl/db_impl.cc:2353
#13 0x00007ffff799f96f in rocksdb::DBImpl::GetImpl (this=this@entry=0x1542900, read_options=..., column_family=column_family@entry=0x7ffff689e360, key=..., value=value@entry=0x7fffce0c5eb0, timestamp=0x0) at db/db_impl/db_impl.cc:2025
#14 0x00007ffff799fc49 in rocksdb::DBImpl::Get (this=0x1542900, _read_options=..., column_family=0x7ffff689e360, key=..., value=0x7fffce0c5eb0, timestamp=0x0) at db/db_impl/db_impl.cc:2013
#15 0x00007ffff7997c99 in rocksdb::DBImpl::Get (this=<optimized out>, read_options=..., column_family=<optimized out>, key=..., value=<optimized out>) at db/db_impl/db_impl.cc:1985
#16 0x00007ffff792034b in rocksdb::DB::Get (this=0x1542900, options=..., column_family=0x7ffff689e360, key=..., value=0x7fffce0c5f80) at ./include/rocksdb/db.h:562
#17 0x00007ffff79011ec in rocksdb_get_cf (db=<optimized out>, options=<optimized out>, column_family=<optimized out>, key=<optimized out>, keylen=<optimized out>, vallen=0xc0004e3e48, errptr=0xc0000d0f10) at db/c.cc:1313
#18 0x0000000000bb4faa in _cgo_f447ecf62de7_Cfunc_rocksdb_get_cf ()
```

**Comment by philmes** [comment]
Seems like a rocksdb thing. Reproduced it in pure c:

```
    #include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>

#include "rocksdb/c.h"

const char DBPath[] = "/tmp/rocksdb_c_simple_example";

void setup() {
    rocksdb_t *db;
    rocksdb_options_t *options = rocksdb_options_create();
    rocksdb_options_set_create_if_missing(options, 1);
    rocksdb_options_set_create_missing_column_families(options, true);

    rocksdb_column_family_handle_t* cfHandles[2];

    char* cfNames[2];
    cfNames[0] = "default";
    cfNames[1] = "metadata";

    rocksdb_options_t* cfOpts[2];
    cfOpts[0] = rocksdb_options_create();
    cfOpts[1] = rocksdb_options_create();

    // open DB
    char *err = NULL;
    db = rocksdb_open_column_families(options, DBPath, 2, (const char**)cfNames,
                                      (const rocksdb_options_t**)cfOpts,
                                      cfHandles, &err
    );
    assert(!err);

    // Put key-value
    rocksdb_writeoptions_t *writeoptions = rocksdb_writeoptions_create();
    const char key[] = "key";
    const char *value = "value";

    rocksdb_put_cf(db, writeoptions, cfHandles[1], key, strlen(key), value, strlen(value)+1, &err);
    assert(!err);

    rocksdb_close(db);
}

void trigger() {
    rocksdb_t *db;
    rocksdb_options_t *options = rocksdb_options_create();
    rocksdb_options_set_create_if_missing(options, 1);
    rocksdb_options_set_create_missing_column_families(options, true);

    rocksdb_column_family_handle_t* cfHandles[2];

    char* cfNames[2];
    cfNames[0] = "default";
    cfNames[1] = "metadata";

    rocksdb_options_t* cfOpts[2];
    cfOpts[0] = rocksdb_options_create();
    cfOpts[1] = rocksdb_options_create();

    // open DB
    char *err = NULL;
    db = rocksdb_open_column_families(options, DBPath, 2, (const char**)cfNames,
                                      (const rocksdb_options_t**)cfOpts,
                                      cfHandles, &err
    );
    assert(!err);

    rocksdb_readoptions_t *readoptions = rocksdb_readoptions_create();
    size_t len;

    const char key[] = "key";
    const char *value;

    char *returned_value = rocksdb_get_cf(db, readoptions, cfHandles[1], key, strlen(key), &len, &err);
    assert(!err);
    assert(strcmp(returned_value, "value") == 0);
    free(returned_value);

    rocksdb_close(db);
}

int main(int argc, char **argv) {
    setup();
    trigger();

    return 0;
}
```

**Comment by linxGnu** [comment]
@philmes thank you for using the library.
Since it's rocksdb matter, let me close this issue. Please feel free to create new one if you face any troubles.
