### ISSUE TITLE
opening more than 11 column families results in error

### ISSUE THREAD

**Issue by hiqsociety** [linxGnu/grocksdb#42]
cfNames = []string{"default", "m", "v", "c", "e", "x", "k", "l", "s", "h", "z", "bxb"}
                        //cfNames = []string{"default", "m", "v", "c", "e", "x", "k", "l", "s", "h", "z", "b", "p"}
                        dbr[i], cfh, err = gorocksdb.OpenDbColumnFamilies(opts[i], defaultDBDir+"/d/"+ks, cfNames, []*gorocksdb.Options{opts[i], opts[i], opts[i], opts[i], opts[i], opts[i], opts[i], opts[i], opts[i], opts[i], opts[i], opts[i]})

````

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x478 pc=0xc41992]

runtime stack:
runtime.throw(0x123210e, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x9062fc, 0xc000207478, 0xc000010588)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc000207448 sp=0xc000207410 pc=0x79123b
git.a.com/a/grocksdb._Cfunc_rocksdb_open_column_families(0x7f4bb919fa00, 0x7f4bb903f260, 0xc, 0xc00005a480, 0xc00001e120, 0xc00001e180, 0xc000010588, 0x0)
        _cgo_gotypes.go:2705 +0x49 fp=0xc000207478 sp=0xc000207448 pc=0x874c29
git.a.com/a/grocksdb.OpenDbColumnFamilies.func1(0xc000059900, 0x7f4bb903f260, 0xc, 0xc0002075d0, 0xc0002075b8, 0xc0002075e8, 0xc000010588, 0x8)
        /root/go/pkg/mod/git.a.com/a/grocksdb@v0.0.0-20210604172949-52e0b4ffcf99/db.go:158 +0x229 fp=0xc0002074e8 sp=0xc000207478 pc=0x878b49
git.a.com/a/grocksdb.OpenDbColumnFamilies(0xc000059900, 0xc000016c80, 0x8, 0xc000168540, 0xc, 0xc, 0xc000207878, 0xc, 0xc, 0x0, ...)
        /root/go/pkg/mod/git.a.com/a/grocksdb@v0.0.0-20210604172949-52e0b4ffcf99/db.go:158 +0x285 fp=0xc000207610 sp=0xc0002074e8 pc=0x875f85
````

**Comment by linxGnu** [comment]
@hiqsociety please sure that number of column family option and number of column family is the same. I could open 16 column families or more without any problem.

PTAL: https://github.com/linxGnu/grocksdb/blob/test_open_many/cf_test.go#L14-L36

**Comment by hiqsociety** [comment]
seems like it doesnt work if you use terarkdb.
can u try it and see what i mean?
